<a href="https://colab.research.google.com/github/jojosam90/cnn/blob/main/labelimg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import imutils

In [10]:
img = cv2.imread("/content/bicycle.jpg")
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [12]:
ret, thresh = cv2.threshold(img_gray, 150, 255, cv2.THRESH_BINARY_INV)
contours, hierarchy = cv2.findContours(image=thresh, mode=cv2.RETR_CCOMP, method=cv2.CHAIN_APPROX_NONE)                                    
image_copy = img.copy()
cv2.drawContours(image=image_copy, contours=contours, contourIdx=-1, color=(0, 255, 0), thickness=2, lineType=cv2.LINE_AA)
contours = np.vstack(contours).squeeze()

cv2.circle(img, (52,159), 8, (0, 0, 255), 100) 

#cv2.imshow('None approximation', image_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
contours.shape

(3238, 2)

In [21]:
contours

array([[ 52, 159],
       [ 57, 157],
       [ 57, 158],
       ...,
       [192,  23],
       [193,  24],
       [192,  25]], dtype=int32)

In [18]:
for i in range(0, len(contours), 500):
    print(contours)

[[ 52 159]
 [ 57 157]
 [ 57 158]
 ...
 [192  23]
 [193  24]
 [192  25]]
[[ 52 159]
 [ 57 157]
 [ 57 158]
 ...
 [192  23]
 [193  24]
 [192  25]]
[[ 52 159]
 [ 57 157]
 [ 57 158]
 ...
 [192  23]
 [193  24]
 [192  25]]
[[ 52 159]
 [ 57 157]
 [ 57 158]
 ...
 [192  23]
 [193  24]
 [192  25]]
[[ 52 159]
 [ 57 157]
 [ 57 158]
 ...
 [192  23]
 [193  24]
 [192  25]]
[[ 52 159]
 [ 57 157]
 [ 57 158]
 ...
 [192  23]
 [193  24]
 [192  25]]
[[ 52 159]
 [ 57 157]
 [ 57 158]
 ...
 [192  23]
 [193  24]
 [192  25]]
